name: Get Next ECR Image Tag
description: Determine the next container image tag for an image in ECR
inputs:
  registry:
    description: The url for the regsitry
    required: true
  repository-name:
    description: The name of the repository for the container image
    required: true
  major-minor-version:
    description: The major.minor version of the container image
    required: false
    default: "1.0"
  pre-release-tag:
    description: "Append a pre-release-tag to the major-minor-version, ex: 1.0-rc.0"
    required: false
    default: ""
outputs:
  next-tag:
    description: The next tag
    value: ${{ steps.get-next-tag.outputs.next-tag }}
  next-image-name:
    description: The full image name with the next tag
    value: ${{ steps.get-next-tag.outputs.next-image-name }}
runs:
  using: composite
  steps:
    - name: Get Next ECR Image Tag
      id: get-next-tag
      shell: pwsh
      run: ${{ github.action_path }}/action.ps1
      env:
        INPUT_REGISTRY: ${{ inputs.registry }}
        INPUT_REPOSITORY_NAME: ${{ inputs.repository-name }}
        INPUT_MAJOR_MINOR_VERSION: ${{ inputs.major-minor-version }}
        INPUT_PRE_RELEASE_TAG: ${{ inputs.pre-release-tag }}
